<div class="p-2">
    <h3>
        Vlastní články
    </h3>
    <?php if (!$is_banned) : ?>
        <div class="pb-2 mb-2 border-bottom border-dark">
            <a class="button new-article" href="moje-clanky/pridat"><i class="fa fa-plus pe-1"></i>Nový</a>
        </div>
    <?php endif ?>

    <?php if (!isset($articles)) : ?>
        <h3 class="d-flex justify-content-center">Žádné články</h3>
    <?php else : ?>
        <?php foreach ($articles as $article) : ?>
            <div class="article">
                <div class="article-header">
                    <em><?=$article['authors']?></em>
                    <h4><?=$article['name']?></h4>
                </div>
                <p class="article-content"><?=$article['abstract']?></p>
                <em class="article-timestamp"><?=$article['timestamp']?></em>
                <?php if (!$is_banned) : ?>
                    <div class="article-controls">
                        <a class="button edit-article" href="moje-clanky/edit?id=<?=$article['id']?>"><i class="fa fa-pencil"></i> Upravit</a><br>
                    </div>
                <?php endif ?>
            </div>
        <?php endforeach ?>
    <?php endif ?>
</div>
<script>
    document.getElementById("navbar-collapsed-text").innerText = "Moje články";
</script>