<div class="p-2">
    <h3>
        Příspěvky
    </h3>
    <?php if ($can_add_article) : ?>
        <div class="pb-2">
            <a class="button new-article" href="prispevky/novy"><i class="fa fa-plus pe-1"></i>Přidat</a>
        </div>
    <?php endif ?>
    <div class="row">
        <div class="col-12 col-sm-6 col-lg-3 mb-4 mb-sm-4 mb-lg-0">
            <div class="article-preview">
                <h4>Návrh 1</h4>
                <p>blblablabblbllablaalblabalalbla b lab l abl balb a balb lb al ablb</p>
                <span>04.11.2021</span>
            </div>
        </div>
        <div class="col-12 col-sm-6 col-lg-3 mb-4 mb-sm-4 mb-lg-0">
            <div class="article-preview">
                <h4>Návrh 2</h4>
                <p>blblablab aosidh oiashdg oihsdoihasdfoi ha</p>
                <span>04.11.2021</span>
            </div>
        </div>
        <div class="col-12 col-sm-6 col-lg-3 mb-4 mb-sm-4 mb-lg-0">
            <div class="article-preview">
                <h4>Návrh 3</h4>
                <p>blblablab jkalds jfkl  kjad fbasobv</p>
                <span>04.11.2021</span>
            </div>
        </div>
        <div class="col-12 col-sm-6 col-lg-3 mb-4 mb-sm-4 mb-lg-0">
            <div class="article-preview">
                <h4>Návrh 4</h4>
                <p>blblablab sdaofi jasdouihf asjdn dsn isjn foiasdng o</p>
                <span>04.11.2021</span>
            </div>
        </div>
    </div>
</div>
<script>
    document.getElementById("uvod").classList.add("selected");
    document.getElementById("navbar-collapsed-text").innerText = "Úvod";
</script>