<div class="p-3">
    <h3>
        Registrace
    </h3>
    <div class="d-flex justify-content-center">
        <form class="register-form" method="post">
            <span class="text-danger" hidden>
                Uživatel se zadaným emailem již existuje.
            </span>
            <table>
                <tr>
                    <td><label for="name">Celé jméno</label></td>
                    <td><input type="text" id="name" name="name" placeholder="..." required onkeyup="checkForm()"></td>
                </tr>
                <tr>
                    <td><label for="username">Uživatelské jméno</label></td>
                    <td><input type="text" id="username" name="username" placeholder="..." required onkeyup="checkForm()"></td>
                </tr>
                <tr>
                    <td><label for="password">Heslo</label></td>
                    <td><input type="password" id="password" name="password" placeholder="..." required onkeyup="checkForm()"/></td>
                </tr>
                <tr>
                    <td><label for="password-confirm">Potvrďte heslo</label></td>
                    <td><input type="password" id="password-confirm" name="password-confirm" placeholder="..." required onkeyup="checkForm()"/></td>
                </tr>
                <tr hidden>
                    <td></td>
                    <td>
                        Hesla se neshodují
                    </td>
                </tr>
                <tr>
                    <td><label for="email">Email</label></td>
                    <td><input type="email" id="email" name="email" placeholder="..." required onkeyup="checkForm()"></td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <button name="submit" type="submit" class="submit"></i>Registrovat</button>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>
<script>
    document.getElementById("uvod").classList.add("selected");
    document.getElementById("navbar-collapsed-text").innerText = "Registrace";
    if (window.history.replaceState) window.history.replaceState(null, null, window.location.href);
</script>