<div class="p-3">
    <h3>
        Aktuality z konference
    </h3>
    <div class="row">
        <div class="col-sm-6 col-lg-3 mb-4 mb-sm-4 mb-lg-0">
            <div class="article-preview">
                <h4 class="p-2 mb-0">
                    Návrh 1
                </h4>
                <p>
                    blblablabblbllablaalblabalalbla b lab l abl balb a balb lb al ablb
                </p>
                <span class="text-end w-100 d-block pe-2">
                    04.11.2021
                </span>
            </div>
        </div>
        <div class="col-sm-6 col-lg-3 mb-4 mb-sm-4 mb-lg-0">
            <div class="article-preview">
                <h4 class="p-2 mb-0">
                    Návrh 2
                </h4>
                <p>
                    blblablab aosidh oiashdg oihsdoihasdfoi ha
                </p>
                <span class="text-end w-100 d-block pe-2">
                    04.11.2021
                </span>
            </div>
        </div>
        <div class="col-sm-6 col-lg-3 mb-4 mb-sm-4 mb-lg-0">
            <div class="article-preview">
                <h4 class="p-2 mb-0">
                    Návrh 3
                </h4>
                <p>
                    blblablab jkalds jfkl  kjad fbasobv
                </p>
                <span class="text-end w-100 d-block pe-2">
                    04.11.2021
                </span>
            </div>
        </div>
        <div class="col-sm-6 col-lg-3 mb-4 mb-sm-4 mb-lg-0">
            <div class="article-preview">
                <h4 class="p-2 mb-0">
                    Návrh 4
                </h4>
                <p>
                    blblablab sdaofi jasdouihf asjdn dsn isjn foiasdng o
                </p>
                <span class="text-end w-100 d-block pe-2">
                    04.11.2021
                </span>
            </div>
        </div>
    </div>
    <p>
        
    </p>
</div>
<script>
    document.getElementById("uvod").classList.add("selected");
    document.getElementById("navbar-collapsed-text").innerText = "Úvod";
</script>