<div class="p-3">
    <h3>Správa uživatelů</h3>
    <div class="overflow-auto">
        <table class="user-management-table">
            <thead>
                <th>Povolen</th>
                <th>Jméno</th>
                <th>Login</th>
                <th>Role</th>
                <th>Akce</th>
            </thead>
            <?php foreach ($users as $user) : ?>
                <tr>
                    <td>
                        <div class="d-flex justify-content-center">
                            <?php if ($user['banned']) : ?>
                                <i class="fa fa-times-circle user-disabled"></i>
                            <?php else : ?>
                                <i class="fa fa-check-circle user-enabled"></i>
                            <?php endif ?>
                        </div>
                    </td>
                    <td><?=$user['full_name']?></td>
                    <td><?=$user['username']?></td>
                    <td><?=$user['name']?></td>
                    <td>
                        <div class="d-flex justify-content-center">
                            <a class="button edit" href="/uzivatele/edit?id=<?= $user['id']?>"><i class="fa fa-edit"></i></a>
                            <a class="button ban" href="/uzivatele/ban?id=<?= $user['id']?>"><i class="fa fa-times-circle"></i></a>
                        </div>
                    </td>
                </tr>
            <?php endforeach ?>
        </table>
    </div>
</div>
<script>
    document.getElementById("navbar-collapsed-text").innerText = "Správa uživatelů";
    if (window.history.replaceState) window.history.replaceState(null, null, window.location.href);
</script>